### ISSUE TITLE
We need to check for commands of ESLint job rather than just name in semaphore config

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-compliance#10]
https://github.com/bigbinary/neeto-compliance/blob/a0f82f0687ab3bcc181294afa0c1bc1c007eed21/lib/neeto_compliance/verifiers/eslint_semaphore_config_verifier.rb#L44
We recently had to update the semaphore config in wheel due to a pressing issue. Refer: https://github.com/bigbinary/wheel/pull/639

But in order for the above change to be enforced in all projects, we'd have to check that current projects' semaphore config has the following lines from `wheel`:
https://github.com/bigbinary/wheel/blob/54f39f4d160d03ac2368939980f8027f6bd1ddec/.semaphore/semaphore.yml#L46-L52

If we don't check for commands, whatever updates we make there won't be reflected to all neeto projects.

@unnitallman _a
Can you please take a look into this? Thanks.

**Comment by yedhink** [comment]
Also we shouldn't hardcoded this config in the message:
https://github.com/bigbinary/neeto-compliance/blob/a0f82f0687ab3bcc181294afa0c1bc1c007eed21/lib/neeto_compliance/verifiers/eslint_semaphore_config_verifier.rb#L10-L29

Those configs can get updated in wheel in the long run. I'd suggest fetching the commands from wheel itself rather than hardcoding.

**Comment by yedhink** [comment]
@unnitallman Can we assign this issue to @arunmkurian with priority? Some folks are facing issues because we aren't handling this case:
https://github.com/bigbinary/neeto-interview-web/pull/229#issuecomment-932029916

**Comment by unnitallman** [comment]
@yedhink I did not foresee that we would change the Eslint script itself.  Now since we know that it could change, could you consider this option: 

```
- name: Eslint
          commands:
            - curl -s -L "https://raw.githubusercontent.com/bigbinary/wheel/master/.scripts/run_eslint_on_changed_files" | bash
```

**Comment by yedhink** [comment]
@unnitallman Let me give that a shot and see how well it works in Semaphore. If it works well, then I will add it to the `sync_with_script`.

**Comment by yedhink** [comment]
@unnitallman I have updated the semaphore config in wheel. The following needs to be done in neeto-compliance. Else the error will persist in all neeto-products.

Changes required in neeto-compliance:
- Check for the first command within the eslint job in semaphore config
- Ensure command is `curl -s -L "https://raw.githubusercontent.com/bigbinary/wheel/master/.semaphore/commands/run_eslint_on_modified_files.sh" | bash`.
- Update the hardcoded information strings to something like:
```
   puts %{ 
           Add Eslint job from wheel to your semaphore.yml as shown below:
           - name: Eslint
             commands:
                - curl -s -L "https://raw.githubusercontent.com/bigbinary/wheel/master/.semaphore/commands/run_eslint_on_modified_files.sh" | bash
  }
```

**Comment by unnitallman** [comment]
I will get this done soon @yedhink @unnitallman _a
