### ISSUE TITLE
Add check for neetoUI version

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-compliance#123]
@unnitallman _a Please look into this.

**Comment by neerajdotname** [comment]
@prasanthchaduvula Can you look into this today? This is a priority issue.

**Comment by prasanthchaduvula** [comment]
@neerajdotname I am on PTO today. Can I work on this on Monday early morning. I don't have laptop with me right now.

**Comment by neerajdotname** [comment]
@prasanthchaduvula that's fine.
