### ISSUE TITLE
Update i18n gem to 1.9.1 as 1.9.0 is yanked

### ISSUE THREAD

**Issue by vishnu-m** [bigbinary/neeto-compliance#125]
I checked in some of the `neeto` repos and wasn't able to run `bundle install` because of this. 

Please take a look:

https://user-images.githubusercontent.com/29692938/151486240-05a9192d-d004-4da9-b264-4a996efa771e.mp4

@unnitallman @prasanthchaduvula

**Comment by neerajdotname** [comment]
The right way would be `bundle update i18n` I think. I haven't tested it. 

Problem with updating manually is that if there is another gem dependent on that gem then that gem's version is not updated. In this case it seems no gem depends on `i18n` or if other gems depends on it then they are fine with `i18n` being upgraded. But the right way would be to use `bundle update gem-name`.

**Comment by vishnu-m** [comment]
Right. Got it.
