### ISSUE TITLE
Heroku env variables for production

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-compliance#138]
https://www.loom.com/share/8e9bfdb3f8af4a21a151cc051d9b6647

**Comment by unnitallman** [comment]
@prasanthchaduvula _a Here is the list of env variables used across all neeto production apps. 
[env_vars.tar.gz](https://github.com/bigbinary/neeto-compliance/files/8023390/env_vars.tar.gz)

**Comment by prasanthchaduvula** [comment]
These are the common variables.
```
APP_URL:
ASSET_HOST:
AUTH_APP_ID:
AUTH_APP_SECRET:
AUTH_APP_URL:
AUTOBUS_URL:
AWS_ACCESS_KEY_ID:
AWS_REGION:
AWS_SECRET_ACCESS_KEY:
DATABASE_URL:
ENABLE_SSO:
HONEYBADGER_API_KEY:
MAILGUN_PASSWORD:
MAILGUN_USERNAME:
NODE_MODULES_CACHE:
NODE_OPTIONS:
RACK_ENV:
RAILS_AUTOSCALE_URL:
RAILS_ENV:
RAILS_LOG_TO_STDOUT:
RAILS_SERVE_STATIC_FILES:
REDIS_CACHE_URL:
REDIS_URL:
SECRET_KEY_BASE:
SERVER_AUTHENTICATION_TOKEN:
YARN_CACHE:
YARN_PRODUCTION:
```

**Comment by prasanthchaduvula** [comment]
@unnitallman _a

**Comment by unnitallman** [comment]
@prasanthchaduvula _a We have covered most of this, as we have moved all ENV variables to secrets.yml. I want us to be in a place where we should be confidently able to say that secrets.yml is the single source of truth for all ENV variables. For this:

1. Make a list of env variables that are used only on production directly. Eg: YARN_PRODUCTION=true, YARN_CACHE=true etc. We will add this is a comment on top of secrets.yml.
2. Scan through neeto-commons, neeto-compliance and other internal gems and see if there are ENV variables that we directly use in them. If found, create issues to move them to secrets.yml as well.

**Comment by prasanthchaduvula** [comment]
Not present In our secrets yml but these used in storage.yml 
```
AWS_ACCESS_KEY_ID
AWS_REGION
AWS_SECRET_ACCESS_KEY
```

 not present in our app completely but present In heroku production 
```
 DATABASE_URL
 MAILGUN_PASSWORD
  MAILGUN_USERNAME 
  RAILS_AUTOSCALE_URL
RAILS_ENV
RAILS_LOG_TO_STDOUT
RAILS_SERVE_STATIC_FILES
```


 not present in our secrets
```
  HONEYBADGER_API_KEY 
  RACK_ENV
```

  only present in app.json of our app but present in production NODE_MODULES_CACHE
```
NODE_OPTIONS
YARN_CACHE
YARN_PRODUCTION
```

**Comment by unnitallman** [comment]
This has been completed by @prasanthchaduvula Refer: https://github.com/bigbinary/neeto-engineering-web/blob/master/production-environment-variables.md
