### ISSUE TITLE
We should maintain the PostgreSQL version throughout the application environments

### ISSUE THREAD

**Issue by sumanranjanpanda** [bigbinary/neeto-compliance#140]
Recently we faced an issue with searching for a form submission. 
It was working fine locally & in staging. But it was throwing `PG::InvalidDatetimeFormat: ERROR:` error in production. 

This error is occurring only in version 13.5. The feature is working in all other versions.

Here are the PostgreSQL versions we are using across the environments
- Development/Locally, it's different in different machines  - 12.1, 14
- Heroku/Review apps - 13.5
- Staging - 12.9
- Production - 13.5

If we will not maintain the version, we might see such undesired output in certain environments.

**Comment by neerajdotname** [comment]
I agree. We need to ensure that there is consistency. In this case the version in staging is different from the version in production. Anytime anything can go wrong and we would end up chasing the issue across all products. It's best that we have a mechanism to control the PG version.

**Comment by prasanthchaduvula** [comment]
@unnitallman _a

**Comment by unnitallman** [comment]
@sumanranjanpanda @neerajdotname Only `neeto-engage-web-staging` and `neeto-form-web-staging` are running older PG version `12.9`. Rest all are on `13.5`. I will upgrade these 2 now.

AppName | PG Version
---|---
neeto-chat-web-staging | 13.5
neeto-chat-web-production | 13.5
neeto-runner-web-staging | 13.5
neeto-runner-web-production | 13.5
neeto-quiz-web-staging | 13.5
neeto-quiz-web-production | 13.5
neeto-invisible-web-staging | 13.5
neeto-kb-web-staging | 13.5
neeto-kb-web-production | 13.5
neeto-hr-web-staging | 13.5
neeto-popups-web-staging | 13.5
neeto-popups-web-production | 13.5
neeto-changelog-web-staging | 13.5
neeto-changelog-web-production | 13.5
neeto-form-web-staging | 12.9
neeto-form-web-production | 13.5
neeto-analytics-web-staging | 13.5
neeto-desk-web-staging | 13.5
neeto-desk-web-production | 13.5
neeto-wireframe-web-staging | 13.5
neeto-wireframe-web-production | 13.5
neeto-invoice-web-staging | 13.5
neeto-invoice-web-production | 13.5
neeto-planner-web-staging | 13.5
neeto-planner-web-production | 13.5
neeto-engage-web-staging | 12.9
neeto-engage-web-production | 13.5
neeto-grow-web-staging | 13.5
neeto-grow-web-production | 13.5
neeto-auth-web-staging | 13.5
neeto-auth-web-production | 13.5
neeto-replay-web-staging | 13.5
neeto-course-web-staging | 13.5
neeto-crm-web-staging | 13.5
neeto-crm-web-production | 13.5
neeto-store-web-staging | 13.5
neeto-store-web-production | 13.5

**Comment by unnitallman** [comment]
Done. Both `neeto-engage-web-staging` and `neeto-form-web-staging` are on PG `13.5` now.

**Comment by unnitallman** [comment]
Now we have 13.5 across review apps, staging and production. On development machines, we can control the PG version only if are asking people to run our Docker file, which I don't think is required since review, staging and production are now in the same version.
