### ISSUE TITLE
Check for config.active_storage.service in development.rb

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/neeto-compliance#160]
The value should be `:local`. 
`config.active_storage.service = :local`

Also, add a check to ensure credentials related to AWS are not committed to any of the `.env` files

**Comment by prasanthchaduvula** [comment]
Standardized this one https://github.com/bigbinary/neeto_commons/blob/9e817fe4a7762240050573fc7040cae020dc5db4/lib/neeto_commons/common_files/config/development.rb#L9
