### ISSUE TITLE
Ensure webpack alias file is named as `alias.js` and not `custom.js`

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-compliance#2]
They might've to update `webpack/development.js` or `environemnt.js` after renaming.

**Comment by neerajdotname** [comment]
@yedhink I'm not very clear on what we are checking here. Could you please elaborate a bit more on this.

**Comment by yedhink** [comment]
@neerajdotname 

- neetoChat: filename is custom.js. [Refer](https://github.com/bigbinary/neeto-chat-web/blob/master/config/webpack/custom.js). 
- neetoForm: filename is alias.js. [Refer](https://github.com/bigbinary/neeto-form-web/blob/master/config/webpack/alias.js).
- neetoWireframe: no such webpack alias file exist - this cripples eslint to an extent.

But in wheel we use the filename as `alias.js`. [Refer](https://github.com/bigbinary/wheel/blob/master/config/webpack/alias.js).

## Why does consistent naming of webpack alias file matter?
- Eslint uses this file to figure out the pathGroups, which determines which all paths within the project are internal modules. Or more accurately we help eslint understand that whatever is defined within `alias.js` are webpack aliases, and thus should be considered as internal modules.
- The import order in JS files is automatically fixed by ESLint by taking into account these ' pathGroups` too.
- Currently in ESLint I have added a hack so that it takes into consideration either `custom.js` or `alias.js`. But that is a hack. The right solution is updating this file's name to be `alias.js` in all neeto projects.

## Expectation from neeto_compliance
- If filename is `custom.js`, then provide steps to update filename to `alias.js` and making corresponding changes in `webpack/environment.js` etc.
- If no such webpack alias file exists in the first place, then ask the developer to add that file and add it to `webpack/environment.js`.

**Comment by neerajdotname** [comment]
The more stuff we need to neeto-compliance the slower it will get. There are things that need to be on every commit and there are things that folks don't change after it is set.

I think this belongs to the latter category. We can add it to the checklist. Once a particular name is given then I don't think folks will change it especially when all neeto products have the same name.

**Comment by yedhink** [comment]
>Once a particular name is given then I don't think folks will change it, especially when all neeto products have the same name.

Agreed. Currently, there is an inconsistency in the naming.

>The more stuff we need to neeto-compliance the slower it will get.

Agreed. This issue is a one-off thing. Once the filename is changed across neeto projects where inconsistency is present, we don't need this check in neeto-compliance.

@unnitallman Can you confirm the preferred name for this webpack alias file for all neeto-products? In wheel it's `alias.js`. If we can agree on the name, then can we ask the tech leads in each project to raise a PR that fixes this issue? Thanks.

**Comment by unnitallman** [comment]
@yedhink For the naming, let us keep it consistent with Wheel.

@neerajdotname Adding checks like this will not slow down neeto-compliance in a noticeable manner. But I agree that is like a one time check, people may not rename it once it set. 

The idea of adding to neeto-compliance is to make sure people make the change in all the repos without fail, and without having to communicate manually.  Verifiers in neeto-compliance will be audited periodically, and the ones which are not relevant anymore can be removed.

In my view, manual interventions through the checklist should be kept to a minimum - only those items which need manual verification Eg: Check if the side bar of the apps follow consistent pattern across the apps.

**Comment by neerajdotname** [comment]
ok. Sounds good.
