### ISSUE TITLE
Rename AREA51_AUTHORIZED_EMAILS to SUPER_ADMIN_EMAILS

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto-compliance#212]
This will involve change in Area51 gem. 
Also env variable rename in production and staging and may the .env.* files as necessary

@prasanthchaduvula _a

**Comment by unnitallman** [comment]
Sidekiq web interface and a few other things will share the email whitelist, same as Area51. Hence thought of making the variable name more generic. What do you think? @neerajdotname

**Comment by neerajdotname** [comment]
@unnitallman I think we should NOT merge. sidekiq is an oprational issue. AREA51 is more for business KPI etc.

**Comment by unnitallman** [comment]
okay.
