### ISSUE TITLE
Verify cypress docker image and Cypress package version in all repos

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto-compliance#225]
We could achieve this by verifying the circle CI configuration in all apps. We could store a copy of it in neeto-commons. 

@dakshavighne2022 Right now is working on upgrading the Docker image so that we have a newwer version of Chrome installed. @dakshavighne2022 Once this is done and tested, please post a link to the latest circleCI config file here (may be from Desk) and we will do the neeto-compliance work to make sure the same config is used in all neeto apps. 

@prasanthchaduvula pick this up once Daksha finishes her work and posts a comment.

**Comment by dakshavighne2022** [comment]
Here is the link to the neetoDesk circleCI config file
[](https://github.com/bigbinary/neeto-desk-web/blob/b35fbd0e40198d6293f344b68e6318b206d22f55/.circleci/config.yml)

cc: @unnitallman @prasanthchaduvula

**Comment by dakshavighne2022** [comment]
Here is the link to the neetoDesk circleCi config
[https://github.com/bigbinary/neeto-desk-web/blob/b35fbd0e40198d6293f344b68e6318b206d22f55/.circleci/config.yml](url)
