### ISSUE TITLE
Setup Cloudfront as the asset host for all neeto products - staging and production

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto-compliance#26]

**Comment by unnitallman** [comment]
Make this change in environments/staging.rb and production.rb for all repos: https://github.com/bigbinary/neeto-chat-web/blob/3d6d3c661d8ca6eb11e72c92daf92c4fde0a829c/config/environments/production.rb#L37

@prasanthchaduvula _a

**Comment by prasanthchaduvula** [comment]
Completed
