### ISSUE TITLE
Add SemaphoreCI for neeto* gems

### ISSUE THREAD

**Issue by ghousemohamed** [bigbinary/neeto-compliance#266]
- [x] neeto_sso
- [x] neeto_notifications
- [x] neeto-team-members-engine
- [x] neeto-area51
- [x] neeto-form-engine
- [x] neeto_payments_engine

**Comment by ghousemohamed** [comment]
@unnitallman For neeto_notifications and neeto-form-engine, I tried adding them as projects in semaphoreCI using the CLI, via `sem init --project-name neeto_* --repo-url https....` as well. They do not seem to work. It's throwing 500 error. In their documentation, they have documentation only for 40x errors.

Would changing the name of the repository possible cause semaphoreCI to pick these projects up on their dashboard, say from `neeto_notifications` => `neeto-notifications`, etc?

**Comment by neerajdotname** [comment]
@ghousemohamed I tried changing name and even that did not work. I've created a ticket for semaphore support. Let's see what they have to say. I even uninstalled semaphore app and reinstalled after 30 minutes. Still it did not work.
