### ISSUE TITLE
The Semaphore CI DB config in all neeto repos use the wrong key

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-compliance#284]
We are supposed to pass in `username`. But the given key is `user`. In some of neeto apps the DB name was being kept as `neetoform_`, example [neetoGrow](https://github.com/bigbinary/neeto-grow-web/blob/74fc294e716a157f7fd066db5cc93f3e8ae2b814/config/database.yml.ci#L9). Since neetoCal was based on top of neetoGrow, this caused some major issues in neetoCal. Refer: https://github.com/bigbinary/neeto-cal-web/pull/98#issuecomment-1111400419

In order to fix the issue, the config was updated: https://github.com/bigbinary/neeto-cal-web/pull/98/commits/5a04fc386050958d5ee4b030efb49a68daa00ee0#diff-c44f142d21edc477c6475769dd432ade4d44a6870e3b32b5b0c632a2da55c44bR7-R14

This is something the compliance should enforce and verify in all applications. We should ensure that the app name is populated based on the git repo.

Something like this:
```yml
<% branch_name = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '') %>
<% repository_name = `git rev-parse --show-toplevel`.split('/').last.strip %>

....rest
  database: <%= "#{repository_name}_development" %>
```

@unnitallman _a Please look into this.

**Comment by unnitallman** [comment]
@prasanthchaduvula _a

**Comment by unnitallman** [comment]
@yedhink 

1. The Ubuntu image used in SemaphoreCI has been upgraded to `ubuntu2004`
2. Database name has been updated based on the git repo name.
