### ISSUE TITLE
Review apps in neetoDesk getting redirected to wrong subdomain 

### ISSUE THREAD

**Issue by ahammednafih** [bigbinary/neeto-compliance#286]
After logging in, the review app is being redirected to https://true.onrender.com/desk/tickets/filters/unresolved as [`HEROKU_APP_NAME`](https://github.com/bigbinary/neeto-desk-web/blob/c2d5f90c8e3cad44a085aa53bb94991747f3197d/render.yaml#L12-L13) is set to true.

@unnitallman _a

Ref link: https://neeto-desk-web-pr-12780.onrender.com/

**Comment by unnitallman** [comment]
Being fixed here: https://github.com/bigbinary/neeto-desk-web/pull/12834
