### ISSUE TITLE
Optimize neeto-audit autofix

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/neeto-compliance#301]
https://www.loom.com/share/02cdd1ad9f3c48ed8f2c1d80fa38039b

**Comment by Amaljith-K** [comment]
@unnitallman Currently the output of `bundle exec neeto-audit` is hidden from developers.
https://github.com/bigbinary/neeto_commons/blob/master/lib/neeto_commons/common_files/.husky/helpers/verify_neeto_audit.sh#L45

Similarly `bundle update <gems>` is hidden too: https://github.com/bigbinary/neeto-compliance/blob/8b32851bf37dbeff9a127f5f19af69a301df4b25/lib/neeto_compliance/runner/auto_correctable.rb#L33

Hiding logs is causing confusion to developers in case it encounters some error. Is there a reason why this is hidden?

**Comment by ghousemohamed** [comment]
@Amaljith-K Let me look into this. The auto_correactable concern is not optimized yet. we should be autocorrecting in the verifier itself.
