### ISSUE TITLE
Ruby version verifier

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-compliance#4]
Ruby version should be 3.0.2

**Comment by neerajdotname** [comment]
@arunmkurian _a 

Arun is joining neeto team from Friday. He will start with neeto-compliance work.

**Comment by unnitallman** [comment]
@arunmkurian For Ruby version check you will need to verify two places: 

1. `.ruby-version` file 
2.  SemaphoreCI config file https://github.com/bigbinary/neeto-analytics-web/blob/neeto_compliance_update/.semaphore/semaphore.yml#L12

**Comment by unnitallman** [comment]
For node version:

1. .node-version
2. .nvmrc
3. package.json (engines section)
4. semaphoreci.yml

**Comment by unnitallman** [comment]
Also go through this write-up by @ghousemohamed which explains the changes needed in `Dockerfile` while upgrading Ruby/Node versions. https://gist.github.com/ghousemohamed/14bf461441186c4c5b3c3bae7f1dc6cf

**Comment by unnitallman** [comment]
@prasanthchaduvula _a

**Comment by yedhink** [comment]
@prasanthchaduvula On second thoughts, given that in wheel the Ruby version is still 3.0.1, let's enforce 3.0.1 itself. No need to encforce 3.0.2 yet.

I have to test how the gems behave in wheel with the new version first.

**Comment by prasanthchaduvula** [comment]
@yedhink will keep 3.0.1 as of now.

**Comment by unnitallman** [comment]
@prasanthchaduvula Pick the version from https://raw.githubusercontent.com/bigbinary/wheel/master/.ruby-version

**Comment by ghousemohamed** [comment]
@prasanthchaduvula Tag me in the PR for this issue so that I can verify how `Dockerfile` changes are being enforced
