### ISSUE TITLE
app.json varies a lot between products 

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-compliance#46]
https://github.com/bigbinary/neeto-wireframe-web/blob/master/app.json

https://github.com/bigbinary/neeto-chat-web/blob/master/app.json

https://github.com/bigbinary/neeto-invisible-web/blob/master/app.json

As we can see `neeto-chat` needs some extra stuff so we can't standardize 100%. However even the `post deploy script` varies a lot which is not good.

**Comment by unnitallman** [comment]
Completed.
