### ISSUE TITLE
Compliance step is failing because of a wrong configuration in a step

### ISSUE THREAD

**Issue by akkshaylawrence** [bigbinary/neeto-compliance#5]
The Neeto compliance step is failing with this error but the highlighted line is invalid in the context of a JSON file. It should be

`"sync_with_wheel": "curl -s -L 'https://raw.githubusercontent.com/bigbinary/wheel/master/.scripts/sync_with_wheel.sh' | bash"`

<img width="1082" alt="Screenshot 2021-09-28 at 12 30 59 PM" src="https://user-images.githubusercontent.com/12969853/135039099-afe5b369-54ef-48ae-9d4b-e0e2f87a8f48.png">

**Comment by yedhink** [comment]
@akkshaylawrence That's a valid point. Can you please make a PR for this? I think only the text needs to be updated over here.

**Comment by akkshaylawrence** [comment]
This issue was fixed in https://github.com/bigbinary/neeto-compliance/commit/638acecd1ebb08ca65194307381ebf3c920d8abe hence closing this issue.
