### ISSUE TITLE
Remove Authentication Flow related test cases from client applications to neeto_sso gem

### ISSUE THREAD

**Issue by ghousemohamed** [bigbinary/neeto-compliance#70]
@unnitallman I think we need to move the test suites which are checking redirection rules, authentication behavior, etc to neeto_sso test suite. What do you think?

**Comment by unnitallman** [comment]
@prasanthchaduvula 

@ghousemohamed Will be preparing a doc with the list of controller tests that need to be removed. @ghousemohamed Please link the doc here once ready.

**Comment by ghousemohamed** [comment]
@prasanthchaduvula https://github.com/bigbinary/neeto_sso/blob/master/API.md Take a look at this doc. All the test cases which are testing these routes need to be removed from all neeto applications.

**Comment by unnitallman** [comment]
@prasanthchaduvula _a Please create an issue in neeto-compliance for this and you can pick up it once you are done with present ones.

**Comment by prasanthchaduvula** [comment]
@unnitallman Instead of creating a new issue I can work on this issue itself which has all the context and this issue is also created in neeto compliance. I have to implement this in all apps individually right?

**Comment by unnitallman** [comment]
Yes sure.

**Comment by sandip-mane** [comment]
Awesome 👏 🙌

**Comment by prasanthchaduvula** [comment]
Completed
