### ISSUE TITLE
Adding collaborators consistency

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-compliance#76]
https://www.loom.com/share/0aaf9b812db74bfe99e5dc8906d08eb2

@unnitallman _a Can you look into it and assign it to someone

**Comment by unnitallman** [comment]
@neerajdotname We are going to build the common team members invitation page. Backend APIs are already built in neeto_sso. @karthiknmenon is looking into the frontend page for this and once done, we will make it into a NPM package which can be used on all (if not all, most) neeto apps. 

@karthiknmenon Let us bump up the priority on this one.

**Comment by unnitallman** [comment]
This has been achieved via neeto-team-members engine gem.
