### ISSUE TITLE
Test makepr, cypress and mergepr labels on all neeto repos

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto-compliance#77]
This is the proposed flow:

Developer creates a PR in draft mode. Once he thinks it is ready for review, he adds `makepr` label. This will check if CI passed and convert PR to ready-for-review mode (from draft). 

Once the reviewers are happy with the PR, they should not merge it manually. They will add `cypress` and `mergepr` labels to the PR. `cypress` label should trigger cypress tests on CircleCI (this starts after a minute of adding the label). Login to https://circleci.com/ with github and you should be able to see the neeto projects there. Also cypress tests will start only after the review app is ready. Once cypress tests are passed, the PR will be automerged (because of the `mergepr` label).

@prasanthchaduvula _a You can create PRs with empty commits to test this.

```
git commit --allow-empty -m "trigger cypress tests"
```

**Comment by unnitallman** [comment]
bug _t

**Comment by prasanthchaduvula** [comment]
@unnitallman _a

**Comment by unnitallman** [comment]
@prasanthchaduvula _a

**Comment by prasanthchaduvula** [comment]
@shreyansh-g24 _a

**Comment by shreyansh-g24** [comment]
Closing this since mergepr has been moved to a worker.
