### ISSUE TITLE
Set cache store as null_store in test environment on all neeto apps

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto-compliance#82]
Example: https://github.com/bigbinary/neeto-chat-web/pull/1833

@prasanthchaduvula _a

**Comment by neerajdotname** [comment]
@prasanthchaduvula If you are up for it then send this fix to Rails. This should be Rails default.

**Comment by prasanthchaduvula** [comment]
> @prasanthchaduvula If you are up for it then send this fix to Rails. This should be Rails default.

@neerajdotname If we create new rails app by default cache store is set to null store in test env.

**Comment by prasanthchaduvula** [comment]
Completed
