### ISSUE TITLE
Include NeetoOrganizationHelpers in the Organization model of all Neeto apps

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto-compliance#83]
https://github.com/bigbinary/neeto_sso/blob/master/app/models/concerns/neeto_sso_organization_helpers.rb

In some apps they have a file called `OrganizationHelpers` included in the Organization model already. If so, have a look at OrganizationHelpers file in that app. 

If there is code in `OrganizationHelpers` which is already present in `NeetoOrganizationHelpers`, then remove the duplicated code from `OrganizationHelpers` file. You can even delete `OrganizationHelpers` file if there is no other code present in it. Do this on a case by case basis on each app.

@prasanthchaduvula _a

**Comment by prasanthchaduvula** [comment]
Completed
